openapi: 3.1.0
info:
  title: ICS File Generator
  version: 1.1.0
  description: >
    Generates downloadable `.ics` calendar files for events.
    Supports specifying time zones for accurate local scheduling.
servers:
  - url: https://ics-api-bp0p.onrender.com
paths:
  /generate:
    post:
      operationId: generateIcsFile
      summary: Generate a downloadable .ics file for a calendar event
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - title
                - startTime
                - endTime
              properties:
                title:
                  type: string
                  description: Title of the event
                description:
                  type: string
                  description: Description of the event
                location:
                  type: string
                  description: Location of the event
                startTime:
                  type: string
                  format: date-time
                  description: >
                    Start time in ISO 8601 format (e.g., "2025-06-15T07:00:00")
                endTime:
                  type: string
                  format: date-time
                  description: >
                    End time in ISO 8601 format (e.g., "2025-06-15T08:00:00")
                timezone:
                  type: string
                  description: >
                    Optional IANA timezone name (e.g., "America/New_York", "Europe/London").
                    If not provided, defaults to UTC.
      responses:
        '200':
          description: A downloadable .ics file URL
          content:
            application/json:
              schema:
                type: object
                properties:
                  downloadUrl:
                    type: string
                    format: uri
                    description: Public URL to download the .ics file
