openapi: 3.1.0
info:
  title: ICS Calendar API
  description: API for generating downloadable .ics calendar files with support for multiple events and time zones.
  version: 1.0.0

servers:
  - url: https://ics-api-bp0p.onrender.com
    description: Production server

paths:
  /generate:
    post:
      operationId: generateIcsFile
      summary: Generate an ICS file containing multiple calendar events.
      description: Accepts a list of events and a timezone, and returns a downloadable `.ics` calendar file.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - timezone
                - events
              properties:
                timezone:
                  type: string
                  description: The user's timezone in IANA format (e.g. America/Chicago)
                  example: America/Chicago
                events:
                  type: array
                  description: List of calendar events to include in the ICS file.
                  items:
                    type: object
                    required:
                      - title
                      - startTime
                      - endTime
                    properties:
                      title:
                        type: string
                        description: Title of the event
                        example: Team Sync Meeting
                      description:
                        type: string
                        description: Description of the event
                        example: Discuss weekly progress
                      location:
                        type: string
                        description: Location of the event
                        example: Zoom
                      startTime:
                        type: string
                        format: date-time
                        description: ISO 8601 start time
                        example: 2025-06-04T15:00:00
                      endTime:
                        type: string
                        format: date-time
                        description: ISO 8601 end time
                        example: 2025-06-04T15:30:00
      responses:
        '200':
          description: Download link for the generated ICS file
          content:
            application/json:
              schema:
                type: object
                properties:
                  downloadUrl:
                    type: string
                    format: uri
                    description: Direct link to download the generated ICS file
                    example: https://ics-api-bp0p.onrender.com/ics/abc123.ics
